[package]
name = "virtiofsd-rs"
description = "A virtio-fs vhost-user device daemon"
version = "0.1.0"
authors = ["The Cloud Hypervisor Authors"]
edition = "2018"
homepage = "https://virtio-fs.gitlab.io/"
repository = "https://gitlab.com/virtio-fs/virtiofsd-rs"
license = "Apache-2.0 AND BSD-3-Clause"
readme = "README.md"

exclude = [".gitlab-ci.yml"]

[dependencies]
bitflags = "1.2"
caps = "0.5"
epoll = "4.3"
futures = { version = "0.3", features = ["thread-pool"] }
libc = "~0.2.87"
log = "0.4"
# Match the version in vmm
seccomp = { git = "https://github.com/firecracker-microvm/firecracker", tag = "v0.22.0" }
structopt = "0.3"
strum = "0.20"
strum_macros = "0.20"
tempdir = "0.3"
vhost-user-backend = { git = "https://github.com/rust-vmm/vhost-user-backend", rev = "3c97ba5" }
vhost = { git = "https://github.com/rust-vmm/vhost", features = ["vhost-user-slave"] }
virtio-bindings = { version = "0.1", features = ["virtio-v5_0_0"] }
vm-memory = "0.4"
vm-virtio = { git = "https://github.com/rust-vmm/vm-virtio" }
vmm-sys-util = "0.7"
